require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'plugins/*/vendor/**/*'

# ════════════════════════════════════════════════════════════
# STRATEGY: Disable all style/layout cops by default.
# Only enable cops that catch REAL BUGS and SECURITY issues.
# We'll tighten over time as the codebase matures.
# ════════════════════════════════════════════════════════════

# Disable entire departments we're not ready for
Style:
  Enabled: false

Layout:
  Enabled: false

Naming:
  Enabled: false

Metrics:
  Enabled: false

# ── Keep only the tabs rule ──
Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Enabled: true
  Width: 2

# ── Lint — catches actual bugs ──
Lint:
  Enabled: true

# Relax specific lint cops that are too noisy for legacy code
Lint/SuppressedException:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

# ── Rails — security and correctness ──
Rails:
  Enabled: false

# Only enable the ones that catch real issues
Rails/OutputSafety:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereExists:
  Enabled: false

# ── RSpec — basic sanity ──
RSpec:
  Enabled: false
