# Disks tab registration (consolidated from plugin)
t = Tab.new("disks", "disks", "/disks")
t.add("index", "disks")
t.add("devices", "devices")
t.add("mounts", "mounts")
t.add("storage_pool", "storage_pool")
