# Network tab registration (consolidated from plugin)
t = Tab.new("network", "network", "/network", nil, true)
t.add("index", "leases")
t.add("hosts", "hosts")
t.add("gateway", "gateway", true)
t.add("dns_aliases", "dns_aliases", true)
t.add("settings", "settings", true)
t.add("remote_access", "remote_access")
t.add("security", "security")
