class Greyhole
  class GreyholeError < StandardError; end

  CONFIG_PATH = '/etc/greyhole.conf'

  class << self
    def enabled?
      return false unless production?
      installed? && running?
    end

    def installed?
      return true unless production?
      system('which greyhole > /dev/null 2>&1')
    end

    def running?
      return false unless production?
      system('systemctl is-active --quiet greyhole')
    end

    def status
      return dummy_status unless production?
      {
        installed: installed?,
        running: running?,
        queue: queue_status,
        pool_drives: pool_drives
      }
    end

    def install!
      return true unless production?
      result = system('apt-get install -y greyhole')
      raise GreyholeError, 'Failed to install greyhole' unless result
      true
    end

    def start!
      return true unless production?
      system('systemctl start greyhole')
    end

    def stop!
      return true unless production?
      system('systemctl stop greyhole')
    end

    def restart!
      return true unless production?
      system('systemctl restart greyhole')
    end

    def pool_drives
      return dummy_pool_drives unless production?
      DiskPoolPartition.all.map do |part|
        usage = part.usage
        {
          path: part.path,
          minimum_free: part.minimum_free,
          total: usage[:total],
          free: usage[:free],
          used: usage[:used]
        }
      end
    end

    def queue_status
      return { pending: 0, last_action: nil } unless production?
      begin
        output = `greyhole --status 2>/dev/null`
        parse_queue_status(output)
      rescue
        { pending: 0, last_action: nil }
      end
    end

    def fsck(options = {})
      return true unless production?
      cmd = 'greyhole --fsck'
      cmd += " --dir=#{Shellwords.escape(options[:dir])}" if options[:dir]
      system(cmd)
    end

    def configure!
      return true unless production?
      config = generate_config
      File.write(CONFIG_PATH, config)
      restart!
    end

    def generate_config
      lines = []
      lines << "# Greyhole configuration - generated by Amahi"
      lines << "# Do not edit manually - changes will be overwritten"
      lines << ""

      # Storage pool drives
      DiskPoolPartition.all.each do |part|
        lines << "storage_pool_drive = #{part.path}, min_free: #{part.minimum_free}gb"
      end
      lines << ""

      # Share settings
      Share.where('disk_pool_copies > 0').each do |share|
        copies = share.disk_pool_copies
        copies_str = copies >= 99 ? 'max' : copies.to_s
        lines << "[#{share.name}]"
        lines << "\tnum_copies = #{copies_str}"
        lines << ""
      end

      lines.join("\n")
    end

    private

    def production?
      defined?(Rails) && Rails.env.production?
    end

    def dummy_status
      {
        installed: false,
        running: false,
        queue: { pending: 0, last_action: nil },
        pool_drives: dummy_pool_drives
      }
    end

    def dummy_pool_drives
      DiskPoolPartition.all.map do |part|
        {
          path: part.path,
          minimum_free: part.minimum_free,
          total: 500_000_000_000,
          free: 250_000_000_000,
          used: 250_000_000_000
        }
      end
    end

    def parse_queue_status(output)
      pending = output.scan(/(\d+) pending/).flatten.first.to_i rescue 0
      { pending: pending, last_action: nil }
    end
  end
end
