require 'rails_helper'

RSpec.describe Greyhole do
  describe '.installed?' do
    it 'returns true in non-production' do
      expect(Greyhole.installed?).to be true
    end
  end

  describe '.running?' do
    it 'returns false in non-production' do
      expect(Greyhole.running?).to be false
    end
  end

  describe '.enabled?' do
    it 'returns false in non-production' do
      expect(Greyhole.enabled?).to be false
    end
  end

  describe '.status' do
    it 'returns a dummy status hash' do
      status = Greyhole.status
      expect(status).to include(:installed, :running, :queue, :pool_drives)
      expect(status[:installed]).to be false
      expect(status[:running]).to be false
      expect(status[:queue]).to eq({ pending: 0, last_action: nil })
    end
  end

  describe '.queue_status' do
    it 'returns dummy queue in non-production' do
      expect(Greyhole.queue_status).to eq({ pending: 0, last_action: nil })
    end
  end

  describe '.generate_config' do
    it 'generates config header with db settings' do
      config = Greyhole.generate_config
      expect(config).to include('# Greyhole configuration - generated by Amahi-kai')
      expect(config).to include('db_host = localhost')
      expect(config).to include('db_user = amahi')
      expect(config).to include('db_name = greyhole')
    end

    it 'includes storage pool drives' do
      create(:disk_pool_partition, path: '/mnt/data1', minimum_free: 10)
      config = Greyhole.generate_config
      expect(config).to include('storage_pool_drive = /mnt/data1, min_free: 10gb')
    end

    it 'includes share copy settings' do
      share = create(:share, name: 'Movies', disk_pool_copies: 2)
      config = Greyhole.generate_config
      expect(config).to include('num_copies[Movies] = 2')
    end

    it 'uses max for copies >= 99' do
      share = create(:share, name: 'Photos', disk_pool_copies: 99)
      config = Greyhole.generate_config
      expect(config).to include('num_copies[Photos] = max')
    end

    it 'excludes shares with zero copies' do
      share = create(:share, name: 'Temp', disk_pool_copies: 0)
      config = Greyhole.generate_config
      expect(config).not_to include('num_copies[Temp]')
    end
  end

  describe '.start!' do
    it 'returns true in non-production' do
      expect(Greyhole.start!).to be true
    end
  end

  describe '.stop!' do
    it 'returns true in non-production' do
      expect(Greyhole.stop!).to be true
    end
  end

  describe '.restart!' do
    it 'returns true in non-production' do
      expect(Greyhole.restart!).to be true
    end
  end

  describe '.install!' do
    it 'returns true in non-production' do
      expect(Greyhole.install!).to be true
    end
  end

  describe '.configure!' do
    it 'returns true in non-production' do
      expect(Greyhole.configure!).to be true
    end
  end

  describe '.fsck' do
    it 'returns true in non-production' do
      expect(Greyhole.fsck).to be true
    end
  end

  describe '.pool_drives' do
    it 'returns dummy data for pool drives' do
      create(:disk_pool_partition, path: '/mnt/test', minimum_free: 5)
      drives = Greyhole.pool_drives
      expect(drives.length).to eq(1)
      expect(drives.first[:path]).to eq('/mnt/test')
      expect(drives.first[:minimum_free]).to eq(5)
      expect(drives.first).to include(:total, :free, :used)
    end
  end
end
