require 'rails_helper'

RSpec.describe Greyhole do
  describe '.installed?' do
    it 'returns true in non-production' do
      expect(Greyhole.installed?).to be true
    end
  end

  describe '.running?' do
    it 'returns false in non-production' do
      expect(Greyhole.running?).to be false
    end
  end

  describe '.enabled?' do
    it 'returns false in non-production' do
      expect(Greyhole.enabled?).to be false
    end
  end

  describe '.status' do
    it 'returns a dummy status hash' do
      status = Greyhole.status
      expect(status).to include(:installed, :running, :queue, :pool_drives)
      expect(status[:installed]).to be false
      expect(status[:running]).to be false
      expect(status[:queue]).to eq({ pending: 0, last_action: nil })
    end
  end

  describe '.queue_status' do
    it 'returns dummy queue in non-production' do
      expect(Greyhole.queue_status).to eq({ pending: 0, last_action: nil })
    end
  end

  describe '.generate_config' do
    it 'generates config header with db settings' do
      config = Greyhole.generate_config
      expect(config).to include('# Greyhole configuration - generated by Amahi-kai')
      expect(config).to include('db_host = localhost')
      expect(config).to include('db_user = amahi')
      expect(config).to include('db_name = greyhole')
    end

    it 'includes storage pool drives' do
      create(:disk_pool_partition, path: '/mnt/data1', minimum_free: 10)
      config = Greyhole.generate_config
      expect(config).to include('storage_pool_drive = /mnt/data1, min_free: 10gb')
    end

    it 'includes share copy settings' do
      share = create(:share, name: 'Movies', disk_pool_copies: 2)
      config = Greyhole.generate_config
      expect(config).to include('num_copies[Movies] = 2')
    end

    it 'uses max for copies >= 99' do
      share = create(:share, name: 'Photos', disk_pool_copies: 99)
      config = Greyhole.generate_config
      expect(config).to include('num_copies[Photos] = max')
    end

    it 'excludes shares with zero copies' do
      share = create(:share, name: 'Temp', disk_pool_copies: 0)
      config = Greyhole.generate_config
      expect(config).not_to include('num_copies[Temp]')
    end
  end

  describe '.start!' do
    it 'returns true in non-production' do
      expect(Greyhole.start!).to be true
    end
  end

  describe '.stop!' do
    it 'returns true in non-production' do
      expect(Greyhole.stop!).to be true
    end
  end

  describe '.restart!' do
    it 'returns true in non-production' do
      expect(Greyhole.restart!).to be true
    end
  end

  describe '.install!' do
    it 'returns true in non-production' do
      expect(Greyhole.install!).to be true
    end
  end

  describe '.configure!' do
    it 'returns true in non-production' do
      expect(Greyhole.configure!).to be true
    end
  end

  describe 'in production' do
    before do
      allow(Greyhole).to receive(:production?).and_return(true)
      allow(Greyhole).to receive(:running?).and_return(true)
      allow(SambaService).to receive(:push_config).and_return(true)
    end

    it 'checks the pool through the root helper while Greyhole runs, and not when it is stopped' do
      allow(Greyhole).to receive(:installed?).and_return(true)
      expect(Greyhole.check_pool!).to be true
      expect(Privileged.calls).to eq([['greyhole.fsck', {}]])
      allow(Greyhole).to receive(:running?).and_return(false)
      expect(Greyhole.check_pool!).to be false
      expect(Privileged.calls.size).to eq(1)
    end

    it 'installs through the root helper in one path, streaming apt output' do
      allow(Privileged).to receive(:call).and_call_original
      allow(Privileged).to receive(:call).with('packages.install', packages: Greyhole::PACKAGES) do |*_args, &block|
        block.call('Setting up greyhole (0.16.4-1) ...')
        { 'ok' => true }
      end
      messages = []

      expect(Greyhole.install! { |msg| messages << msg }).to be true

      expect(Privileged.calls.map(&:first)).to eq(%w[packages.add_repository greyhole.setup_database greyhole.write_config
                                                     greyhole.setup_database services.restart services.enable])
      expect(Privileged.calls.last).to eq(['services.enable', { service: 'greyhole' }])
      expect(messages).to include('  Setting up greyhole (0.16.4-1) ...')
      expect(SambaService).to have_received(:push_config)
    end

    describe 'removing a drive' do
      let!(:going) { create(:disk_pool_partition, path: '/mnt/storage-1', minimum_free: 10) }
      let(:gib) { 1024**3 }

      before do
        allow(Greyhole).to receive(:installed?).and_return(true) # it's dpkg's answer in production
        allow(Greyhole).to receive(:configure!).and_return(true)
        allow(Greyhole).to receive(:mounted_uuid).and_return('uuid')
        allow(Greyhole).to receive(:holds_files?).and_return(true)
        allow_any_instance_of(DiskPoolPartition).to receive(:usage).and_return(total: 20 * gib, free: 18 * gib, used: 2 * gib)
      end

      it 'takes a drive with no files on it out at once' do
        allow(Greyhole).to receive(:holds_files?).and_return(false)
        expect(Greyhole.remove_drive!('/mnt/storage-1')).to eq(:removed)
        expect(DiskPoolPartition.exists?(path: '/mnt/storage-1')).to be false
        expect(Greyhole).to have_received(:configure!)
        expect(Privileged.calls).to be_empty
      end

      it "won't remove the only drive, or one while Greyhole is stopped, or without room on the others" do
        expect { Greyhole.remove_drive!('/mnt/storage-1') }.to raise_error(Greyhole::GreyholeError, /only drive/)
        other = create(:disk_pool_partition, path: '/mnt/storage-2', minimum_free: 10)
        allow(Greyhole).to receive(:running?).and_return(false)
        expect { Greyhole.remove_drive!('/mnt/storage-1') }.to raise_error(Greyhole::GreyholeError, /Start Greyhole first/)
        allow(Greyhole).to receive(:running?).and_return(true)
        allow_any_instance_of(DiskPoolPartition).to receive(:usage) do |part|
          part == other ? { total: 20 * gib, free: 11 * gib, used: 9 * gib } : { total: 20 * gib, free: 18 * gib, used: 2 * gib }
        end
        expect { Greyhole.remove_drive!('/mnt/storage-1') }.to raise_error(Greyhole::GreyholeError, /don't have room/)
        expect(Privileged.calls).to be_empty
      end

      it "has Greyhole move its files, keeping it in the pool until Greyhole has taken it out of greyhole.conf" do
        create(:disk_pool_partition, path: '/mnt/storage-2', minimum_free: 10)
        expect(Greyhole.remove_drive!('/mnt/storage-1')).to eq(:removing)
        expect(Privileged.calls).to eq([['greyhole.remove_drive', { path: '/mnt/storage-1', available: true }]])
        expect(going.reload).to be_removing
        expect(Greyhole.remove_drive!('/mnt/storage-1')).to eq(:removing) # asked again: already under way

        allow(Greyhole).to receive(:configured_drives).and_return(%w[/mnt/storage-1 /mnt/storage-2])
        Greyhole.sync_removals!
        expect(DiskPoolPartition.exists?(path: '/mnt/storage-1')).to be true
        allow(Greyhole).to receive(:configured_drives).and_return(%w[/mnt/storage-2])
        Greyhole.sync_removals!
        expect(DiskPoolPartition.exists?(path: '/mnt/storage-1')).to be false
      end

      it 'says to wait while Greyhole is still checking the files' do
        create(:disk_pool_partition, path: '/mnt/storage-2', minimum_free: 10)
        allow(Privileged).to receive(:call).with('greyhole.remove_drive', anything)
                                           .and_raise(Privileged::Error.new('greyhole.remove_drive', 'greyhole exited 2: '))
        expect { Greyhole.remove_drive!('/mnt/storage-1') }.to raise_error(Greyhole::GreyholeError, /still checking the pool's files/)
        expect(going.reload).not_to be_removing
      end
    end

    describe 'turning a share off' do
      let!(:share) { create(:share, name: 'Photos') }

      before do
        share.update_column(:disk_pool_copies, 2)
        create(:disk_pool_partition, path: '/mnt/storage-1', minimum_free: 10)
        allow(Greyhole).to receive(:installed?).and_return(true)
        allow(Greyhole).to receive(:configure!).and_return(true)
        allow(Greyhole).to receive(:share_on_drives?).and_return(true)
      end

      it 'turns a share with no files on the drives off at once' do
        allow(Greyhole).to receive(:share_on_drives?).and_return(false)
        expect(Greyhole.remove_share!(share)).to eq(:removed)
        expect(share.reload).to have_attributes(disk_pool_copies: 0, pool_removing?: false)
        expect(Greyhole).to have_received(:configure!)
        expect(Privileged.calls.map(&:first)).not_to include('greyhole.remove_share')
      end

      it "has the apps given the share, or every pooled share, follow once Greyhole is done" do
        allow(DockerApp).to receive(:follow_pool!)
        share.update!(pool_removing: true)
        DiskPoolPartition.create!(path: '/mnt/storage-2', minimum_free: 10, removing: true)
        allow(Greyhole).to receive(:configured_drives).and_return(['/mnt/storage-1', '/mnt/storage-2'])
        allow(Greyhole).to receive(:configured_shares).and_return(['Photos'])
        Greyhole.sync_removals!
        expect(DockerApp).not_to have_received(:follow_pool!)

        allow(Greyhole).to receive(:configured_drives).and_return(['/mnt/storage-1'])
        allow(Greyhole).to receive(:configured_shares).and_return([])
        Greyhole.sync_removals!
        expect(DockerApp).to have_received(:follow_pool!).with(no_args).once
        expect(DockerApp).to have_received(:follow_pool!).with(shares: ['Photos']).once
      end

      it "has Greyhole move its files back, keeping it pooled until Greyhole has taken it out of greyhole.conf" do
        expect(Greyhole.remove_share!(share)).to eq(:removing)
        expect(Privileged.calls).to eq([['greyhole.remove_share', { share: 'Photos' }]])
        expect(share.reload).to have_attributes(disk_pool_copies: 2, pool_removing?: true)
        expect(Greyhole.remove_share!(share)).to eq(:removing) # asked again: already under way
        expect(Privileged.calls.size).to eq(1)

        allow(Greyhole).to receive(:configured_drives).and_return(['/mnt/storage-1'])
        allow(Greyhole).to receive(:configured_shares).and_return(['Photos'])
        Greyhole.sync_removals!
        expect(share.reload).to be_pool_removing
        allow(Greyhole).to receive(:configured_shares).and_return([])
        Greyhole.sync_removals!
        expect(share.reload).to have_attributes(disk_pool_copies: 0, pool_removing?: false)
        expect(DiskPoolPartition.exists?(path: '/mnt/storage-1')).to be true
      end

      it "won't while Greyhole is stopped, and passes on the helper's reason" do
        allow(Greyhole).to receive(:running?).and_return(false)
        expect { Greyhole.remove_share!(share) }.to raise_error(Greyhole::GreyholeError, /Start Greyhole first/)
        allow(Greyhole).to receive(:running?).and_return(true)
        allow(Privileged).to receive(:call).with('greyhole.remove_share', anything)
                                           .and_raise(Privileged::Error.new('greyhole.remove_share', "the share's folder doesn't have room"))
        expect { Greyhole.remove_share!(share) }.to raise_error(Greyhole::GreyholeError, /doesn't have room/)
        expect(share.reload).to have_attributes(disk_pool_copies: 2, pool_removing?: false)
      end

      it 'counts a share as on the drives when a pool folder of it has files' do
        allow(Greyhole).to receive(:share_on_drives?).and_call_original
        Dir.mktmpdir do |drive|
          DiskPoolPartition.update_all(path: drive)
          expect(Greyhole.share_on_drives?(share)).to be false
          FileUtils.mkdir_p("#{drive}/Photos")
          expect(Greyhole.share_on_drives?(share)).to be false
          File.write("#{drive}/Photos/a.jpg", 'x')
          expect(Greyhole.share_on_drives?(share)).to be true
        end
      end
    end

    it "reads Greyhole's record of its drives, and says which drive it won't use" do
      records = 'a:3:{s:14:"/mnt/storage-1";s:4:"uuid";s:14:"/mnt/storage-2";s:3:"old";s:14:"/mnt/storage-3";b:0;}'
      parsed = Greyhole.parse_drive_records(records)
      expect(parsed).to eq('/mnt/storage-1' => 'uuid', '/mnt/storage-2' => 'old', '/mnt/storage-3' => nil)
      allow(Greyhole).to receive(:mounted_uuid) { |path| { '/mnt/storage-1' => 'uuid', '/mnt/storage-2' => 'new', '/mnt/storage-4' => 'x' }[path] }
      expect(%w[/mnt/storage-1 /mnt/storage-2 /mnt/storage-4 /mnt/storage-5].map { |path| Greyhole.drive_state(path, parsed) })
        .to eq(%i[ok changed new not_mounted])
      expect(Greyhole.accept_drive!('/mnt/storage-2')).to be true
      expect(Privileged.calls).to include(['greyhole.replace_drive', { path: '/mnt/storage-2' }])
    end

    it "looks for Greyhole's daemon without a shell, whose own command line would match" do
      allow(Greyhole).to receive(:running?).and_call_original
      allow(Open3).to receive(:capture3).with('pgrep', '-f', 'greyhole --daemon')
                                        .and_return(['', '', instance_double(Process::Status, success?: false)])
      expect(Greyhole.running?).to be false
      allow(Open3).to receive(:capture3).with('pgrep', '-f', 'greyhole --daemon')
                                        .and_return(["4242\n", '', instance_double(Process::Status, success?: true)])
      expect(Greyhole.running?).to be true
    end

    it 'uninstalls only when no drive is in its pool and no share keeps copies with it' do
      create(:disk_pool_partition, path: '/mnt/storage-1', minimum_free: 10)
      expect(Greyhole.removal_blocker).to eq('Take its drives out of the storage pool first.')
      expect { Greyhole.uninstall! }.to raise_error(Greyhole::GreyholeError, 'Take its drives out of the storage pool first.')
      DiskPoolPartition.delete_all
      create(:share, name: 'Photos', disk_pool_copies: 2)
      expect(Greyhole.removal_blocker).to eq('The share Photos keeps copies with Greyhole: turn that off on Shares first.')
      Share.update_all(disk_pool_copies: 0)
      expect(Greyhole.removal_blocker).to be_nil
      Privileged.reset! # saving the share above may have written Greyhole's config

      expect(Greyhole.uninstall!).to be true
      expect(Privileged.calls.map(&:first)).to eq(%w[greyhole.uninstall services.restart])
      expect(SambaService).to have_received(:push_config)
    end

    it "stops with the helper's reason" do
      allow(Privileged).to receive(:call).and_raise(Privileged::Error.new('packages.add_repository', 'fingerprint not pinned'))
      expect { Greyhole.install! }.to raise_error(Greyhole::GreyholeError, 'fingerprint not pinned')
    end

    it 'writes the config through the helper and restarts Greyhole when it runs' do
      create(:disk_pool_partition, path: '/mnt/storage-1', minimum_free: 10)
      expect(Greyhole.configure!).to be true
      op, args = Privileged.calls.first
      expect(op).to eq('greyhole.write_config')
      expect(args[:content]).to include('storage_pool_drive = /mnt/storage-1, min_free: 10gb')
      expect(Privileged.calls.last).to eq(['services.restart', { service: 'greyhole' }])
    end

    it 'writes only lines the root helper accepts' do
      create(:disk_pool_partition, path: '/mnt/storage-1', minimum_free: 10)
      share = create(:share, name: 'Movies')
      share.update_column(:disk_pool_copies, 2)
      Privileged.operations # loads libexec/amahi-helper
      expect { AmahiHelper.greyhole_conf(Greyhole.generate_config) }.not_to raise_error
    end

    it 'reports a refused config instead of raising' do
      allow(Privileged).to receive(:call).and_raise(Privileged::Error.new('greyhole.write_config', 'refused'))
      expect(Greyhole.configure!).to be false
    end

    it 'starts, stops and restarts through the helper' do
      Greyhole.start!
      Greyhole.stop!
      Greyhole.restart!
      expect(Privileged.calls.map(&:first)).to eq(%w[services.start services.stop services.restart])
    end
  end

  describe '.pool_drives' do
    it 'returns dummy data for pool drives' do
      create(:disk_pool_partition, path: '/mnt/test', minimum_free: 5)
      drives = Greyhole.pool_drives
      expect(drives.length).to eq(1)
      expect(drives.first[:path]).to eq('/mnt/test')
      expect(drives.first[:minimum_free]).to eq(5)
      expect(drives.first).to include(:total, :free, :used)
    end
  end
end
