# Amahi Home Server
# Copyright (C) 2007-2013 Amahi
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

require 'shell'
require 'shellwords'

class DnsAlias < ApplicationRecord

  after_save :restart
  after_destroy :restart

  scope :user_visible,->{where(["address != ?", ''])}

  validates :name, presence: true, uniqueness: true, format: { with: /\A[a-z][a-z0-9-]*\z/i }

  protected

  def restart
    regenerate_dnsmasq_config
    reload_dnsmasq
  end

  private

  def regenerate_dnsmasq_config
    lines = ["# Auto-generated by Amahi-kai — do not edit manually"]
    DnsAlias.all.each do |a|
      if a.address.present?
        lines << "address=/#{a.name}/#{a.address}"
      else
        lines << "address=/#{a.name}/"
      end
    end

    FileUtils.mkdir_p(HDA_TMP_DIR)
    staged_file = File.join(HDA_TMP_DIR, "amahi-aliases.conf")
    File.write(staged_file, lines.join("\n") + "\n")

    Shell.run("cp #{Shellwords.escape(staged_file)} /etc/dnsmasq.d/amahi-aliases.conf")
  end

  def reload_dnsmasq
    Shell.run("systemctl restart dnsmasq.service")
  end

end
