# Amahi Home Server
# Copyright (C) 2007-2013 Amahi
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

class DnsAlias < ApplicationRecord

	after_save :restart
	after_destroy :restart

	scope :user_visible,->{where(["address != ?", ''])}

	validates :name, presence: true, uniqueness: true, format: { with: /\A[a-z][a-z0-9-]*\z/i }
	# Address can be empty (points to our own address) or a valid IP
	#validates :address, presence: true, uniqueness: true, numericality: { greater_than: 0, less_than: 255 }

	protected

	def restart
		regenerate_dnsmasq_config
		reload_dnsmasq
	end

	private

	# Generate /etc/dnsmasq.d/amahi-aliases.conf from all dns_aliases
	def regenerate_dnsmasq_config
		# Build config lines: address=/name/address (or address=/name/ for self)
		lines = ["# Auto-generated by Amahi-kai — do not edit manually"]
		DnsAlias.all.each do |a|
			if a.address.present?
				lines << "address=/#{a.name}/#{a.address}"
			else
				# Empty address means point to this server's own IP
				lines << "address=/#{a.name}/"
			end
		end

		# Write to HDA tmp dir, then copy into place via sudo cp (matches sudoers allowlist)
		FileUtils.mkdir_p(HDA_TMP_DIR)
		staged_file = File.join(HDA_TMP_DIR, "amahi-aliases.conf")
		File.write(staged_file, lines.join("\n") + "\n")

		c = Command.new("cp #{Shellwords.escape(staged_file)} /etc/dnsmasq.d/amahi-aliases.conf")
		c.execute
	end

	def reload_dnsmasq
		# dnsmasq reload (SIGHUP) does not re-read new files added to conf-dir,
		# so we must restart to pick up newly created config files.
		c = Command.new("systemctl restart dnsmasq.service")
		c.execute
	end

end
